micronaut:
    application:
        name: music-service
    server:
        port: 8080
        cors:
            enabled: true
    router:
        static:
            resources:
                enabled: true
                mapping: /**
                paths: classpath:public
